##################### Adjectives #######################
base_adjectives = {
    "horror_movie_adj" : ["undead", "reborn", "reanimated", "blood-soaked", "cannibal", "cannibalistic", "charnel", "grind-", "grind", "chainsaw", "bloody", "slasher", "gore-encrusted", ],
    "magical_adj": [ "hexed", "accursed", "magic", "magical", "supernatural", "telepathic", "voodoo", "telekinetic", "precognitive", "clairvoyant", "pyrokinetic", "vedic", "sorcerous", "cursed", "forbidden", "mysterious", "ghost", "ghostly", ],
    "natural_adj" : [ "chitinous", "flaming", "fiery", "psycho-", "flying", "albino", "amorphous", "frozen", "burning", "backwoods", "blood-sucking", "chimeric", "dead", "flesh-eating", "fungal", "gelatinous", "heavy", "jungle", "living", "man-eating", "nocturnal", "protoplasmic", "rabid", "sentient", "starving", "untamed", "wild", "woodland", ],
    "old_adj" : [ "eldrich", "prehistoric", "medieval", "long-lost", "lost", "primal", "primeval", "forgotten", "cyclopean", "ancient", "abandoned", "primordial", ],
    "silly_adj" : ["biblically-accurate", "teenage", "surfing", "strange", "weird", "convulsing",
                   "new-wave", "middle-age", "undercover"],
    "wonderous_adj" : [ "amazing", "fantastic", "glorious", "incredible", "mystical", "terrible", ],
    "color": ["brown", "beryl", "chromatic", "emerald", "scarlet", "ruby", "onyx", "purple", "copper", "golden", "silver", "red", "green", "black", "white", "blue", "orange", "yellow", "obsidian", "ebon", "cobalt", "azure"],
    "unseen_adj": ["invisible", "immaterial", "empty", "vacant", "phantom", "subterranean", "transparent", ],
    "material_adj" : ["water", "fire", "earth", "stone", "iron", "metal", "stainless steel", "titanium", "aluminum", "cobalt", "plutonium", "thorium", "uranium", "gold", "silver", "lead", "wax", "clay", "crystal", "bone", "hollow", "glowing", "shining", "glittering", "stainless"],
    "cosmic_adj": ["spectral", "shuddering", "silent", "ruined", "lovecraftian", "non-euclidean", "hallucinogenic", "terminal", "alien", "astral", "cosmic", "crawling", "endless", "eternal", "final", "gibbous", "gloaming", "groaning", "hoary", "indescribable", "infinite", "occult", "outer", "star", "stygian", "timeless", ],
    "size_related_adj": ["hung", "retro", "micro", "micro-", "mega", "mega-", "shrinking", "giant", "transforming", "colossal", "titanic", "enormous", "indestructible", "mighty", ],
    "sexploitation_adj": ["nude", "perky", "moist", "sex-change", "sensual", "buxom", "well-endowed", "passionate", "transsexual", "foxy", "immoral", "kinky", "BDSM", "promiscuous", "raunchy", "dirty", "hedonistic", "desperate", "pent-up", "carnal", "freaky", "deviant", "fleshy", "sexy", "disco", "free-love", "pleasurable", "lavacious", "lecherous", "leather", "buff", "horny", "gay", "lesbian", "trans", "transvestite"],
    "space_age_adj" : ["modern", "chemical", "video", "film", "experimental", "light", "robo-", "astro", "rocket", "solar", "genetic", "neon", "space", "mecha-", "mechano-", "machine", "techno-", "electric", "electro-mechanical", "cybernetic", "stellar", "turbo", "uber-", "photonic", "temporal", "holographic", "time", "transdimensional", "ultra", "futuristic", "techno", "space age", ],
    "decayed_adj" : ["wet", "burning", "ashen", "paralyzing", "caustic", "acrid", "bubbling", "demolished", "diseased", "disgusting", "dying", "fetid", "melting", "one-eyed", "putrid", "rotting", "nuclear", "atomic", "radioactive", "toxic", "mutated", "bloated"],
    "evil_adj" : ["killer", "twisted", "abominable", "aggressive", "corrupt",
                  "dark", "deadly", "demon", "demonic", "depraved", "deranged", "dread",
                  "dreadful", "evil", "ferocious", "godless", "grim", "haunted",
                  "homicidal", "horrifying", "infernal", "inhuman", "insane",
                  "insidious", "murderous", "killer", "laughing", "lurking",
                  "macabre", "mad", "remorseless", "satanic", "shadowy",
                  "sinister", "skeletal", "spooky", "terrifying", "unstoppable",
                  "vampiric", "violent", "mindless", "wrathful", "enraged",
                  "furious", "damned", "doomed", "fallen", "unholy"],
    "hippy_adj": ["vegetarian", "vegan", "psychedelic", "hippy", "trippy", "disorienting", "drugged-out"],
    "religion_or_culture_adj" : [ "noble", "highborn", "Mayan", "Aztec",
                                 "eastern", "#cardinal_direction#ern",
                                 "christian", "jewish", "holy", "sacred",
                                 "hebrew", "Mormon", "neanderthal", "heathen",
                                 "shamanistic", "Norse", "soviet", "communist",
                                 "Scandanavian", "soviet-bloc"],
    "evocative_nations": ["Yugoslavian", "French", "Italian", "Armenian",
                          "Brazilian", "Mexican", "Russian", "Egyptian",
                          "Chinese", "German", "Canadian", "Swedish", "Texas"],
}
