import tracery
from tracery.modifiers import base_english

RULES = {

    "shortform": ["#threat.capitalizeAll#"],
    "shortpluralform": ["#threat.s.capitalizeAll#"],

    "form": [
        "#shortform#",
        "#shortform#",
        "#adj.capitalizeAll# #shortform#",
        "#adj.capitalizeAll# #shortform#"
    ],

    "pluralform": [
        "#shortpluralform#",
        "#shortpluralform#",
        "#adj.capitalizeAll# #threat.s.capitalizeAll#",
        "#adj.capitalizeAll# #threat.s.capitalizeAll#"
    ],

    "origin": [
        "#form#!",
        "#form#!",
        "#form.capitalizeAll# VS. #form#",
        "#form.capitalizeAll# VS. #form#",
        "#form.capitalizeAll# VS. #form#",
        "#form.capitalizeAll# VS. #form#",
        "#pluralform# from #place.capitalizeAll#",
        "#pluralform# from #place.capitalizeAll#",
        "#pluralform# from #place.capitalizeAll#",
        "#pluralform# from #place.capitalizeAll#",
        "#pluralform# from #place.capitalizeAll#",
        "#pluralform# from #place.capitalizeAll#",
        "#pluralform# from #place.capitalizeAll#",
        "#pluralform# from #place.capitalizeAll#",
        "#object.capitalizeAll# of the #form#",
        "#object.capitalizeAll# of the #form#",
        "#object.capitalizeAll# of the #form#",
        "#object.capitalizeAll# of the #form#",
        "#object.capitalizeAll# of the #form#",
        "#object.capitalizeAll# of the #form#",
        "#object.capitalizeAll# of the #form#",
        "#object.capitalizeAll# of the #form#",
        "#object.capitalizeAll# of the #form#",
        "#object.capitalizeAll# of the #form#",
        "#object.capitalizeAll# of the #form#",
        "#object.capitalizeAll# of the #form#",
        "#shortform# #job.capitalizeAll#",
        "#shortform# #job.capitalizeAll#",
        "#shortform# #job.capitalizeAll#",
        "#shortform# #job.capitalizeAll#",
        "#job.capitalizeAll# #shortform# and the #form# from #place.capitalizeAll#",
        "#job.capitalizeAll# #shortform# and the #shortform# from #place.capitalizeAll#",
        "#shortform# #object.capitalizeAll#",
        "#shortform# #object.capitalizeAll#",
        "#shortform# #object.capitalizeAll#",
        "#shortform# #object.capitalizeAll#",
        "#shortform# #object.capitalizeAll#",
        "#shortform# #object.capitalizeAll#",
        "#shortform# #object.capitalizeAll#",
        "#shortform# #object.capitalizeAll#",
        "#shortform# #object.capitalizeAll#",
        "#shortform# #object.capitalizeAll#",
        "#shortform# #object.capitalizeAll#",
        "#shortform# #object.capitalizeAll#",
        "The #form# from #place.capitalizeAll#",
        "The #form# from #place.capitalizeAll#",
        "The #form# from #place.capitalizeAll#",
        "The #form# from #place.capitalizeAll#",
        "The #form# from #place.capitalizeAll#",
        "The #form# from #place.capitalizeAll#",
        "The #form# from #place.capitalizeAll#",
        "The #form# from #place.capitalizeAll#",
        "The #shortform# from #place.capitalizeAll#",
        "The #shortform# from #place.capitalizeAll#",
        "The #shortform# from #place.capitalizeAll#",
        "The #shortform# from #place.capitalizeAll#",
        "The #shortform# from #place.capitalizeAll#",
        "The #shortform# from #place.capitalizeAll#",
        "The #shortform# from #place.capitalizeAll#",
        "The #shortform# from #place.capitalizeAll#",
        "The #form#",
        "The #form#",
        "The #object.capitalizeAll# of #pluralform#",
        "The #object.capitalizeAll# of #pluralform#",
        "The #object.capitalizeAll# of #pluralform#",
        "The #object.capitalizeAll# of #pluralform#",
        "The #object.capitalizeAll# of #pluralform#",
        "The #object.capitalizeAll# of #pluralform#",
        "The #object.capitalizeAll# of #pluralform#",
        "The #object.capitalizeAll# of #pluralform#",
        "The #object.capitalizeAll# of #pluralform#",
        "The #object.capitalizeAll# of #pluralform#",
        "The #object.capitalizeAll# of #pluralform#",
        "The #object.capitalizeAll# of #pluralform#",
        "The #object.capitalizeAll# of the #pluralform#",
        "The #object.capitalizeAll# of the #pluralform#",
        "The #object.capitalizeAll# of the #pluralform#",
        "The #object.capitalizeAll# of the #pluralform#",
        "The #object.capitalizeAll# of the #pluralform#",
        "The #object.capitalizeAll# of the #pluralform#",
        "The #object.capitalizeAll# of the #pluralform#",
        "The #object.capitalizeAll# of the #pluralform#",
        "The #object.capitalizeAll# of the #pluralform#",
        "The #object.capitalizeAll# of the #pluralform#",
        "The #object.capitalizeAll# of the #pluralform#",
        "The #object.capitalizeAll# of the #pluralform#",
        "#shortform#-Geddon",
        "#shortform#-nado",
        "#shortform#-zilla VS #shortform#-ra",
        "#shortform#-zilla",
		"#silly_prefix# #form#",
		"#silly_prefix# #form#",
		"#silly_prefix# #form#",
		"#silly_prefix# #form#",
		"#adj.capitalizeAll# #job.capitalizeAll#: The #object.capitalizeAll# of the #form#",

		"#adj.capitalizeAll# #object.capitalizeAll#",
		"The #adj.capitalizeAll# #adj.capitalizeAll# #shortform#",
        "30 #threat.s.capitalizeAll# 30 Days",
        "#substance.capitalizeAll# #shortform#",
        "I Walked with #pluralform#",
		"The #form# that Wouldn't Die#",
		"#place.capitalizeAll# in 80 Days",

		"#place.capitalizeAll# #number#: The #form#",
		"#place.capitalizeAll# #number#: Return of the #form#",
		"#place.capitalizeAll# #number#: #form# #object.capitalizeAll#",
		"#place.capitalizeAll# #number#: #object.capitalizeAll# of the #form#",
		"#form# #number#: #place.capitalizeAll#",
		"The #form# #number#: #place.capitalizeAll#",

        "#form# de Sade",
        "Sex Slaves of the #form#",
        "The Loves of the #form#",
        "Sexy #threat.s.capitalizeAll# in Cages",
        "The #pluralform# Lovers",
        "The #pluralform# in Leather",
        "Beyond the Valley of the #pluralform#"
    ],

	"number": [
		"2", "3", "4", "5", "6", "II", "III", "IV", "V", "VI", "VII"
	],

	"silly_prefix": [
		"Code Name:",
		"Danger!!",
		"The Wild Wild World of the",
        "Death by",
        "I Married a",
		"Fear the",
		"Dread the",
        "I Walked with the",
        "I Became a",
        "My Wife is a",
        "I Was a Teenage"
	],

    "object": [
        "attack",
        "revenge",
		"escape", 
		"battlefield",
		"dream",
		"adventure",
        "blood",
        "night",
        "bride",
        "mate",
        "mask", 
		"crater",
		"island",
        "legend",
		"bloodbath",
		"betrayal",
		"lies",
		"promises",
		"wishes",
        "vigil",
        "eyes",
		"mine",
        "massacre",
        "city",
        "house",
        "horror",
		"mutiny",
		"tower",
		"keep",
		"dungeon",
		"torture chamber",
        "call",
		"realm",
		"domain",
        "death",
        "day",
		"hive",
		"empire",
		"tome",
		"book",
		"shards",
		"crystal ball",
		"sign",
        "revenge",
        "pit",
		"time",
		"stench",
		"the million eyes", 
		"footprints",
		"throne",
		"cave",
		"holocaust",
		"valhalla",
		"trail",
        "fortress",
		"castle",
		"tentacle",
		"tentacles",
		"fate",
		"ring",
		"rings",
		"planet",
		"echoes",
		"grudge",
		"plot",
		"fellowship",
		"hunt",
		"tomb",
		"mausoleum",
		"vault",
		"crypt",
		"grave",
		"plan",
		"reign",
		"monarchy",
		"madness",
		"sword",
		"gun",
		"stare",
		"track",
		"laugh",
		"hills",
		"sepulcher",
		"embrace",
		"cult",
		"defender",
        "hotel",
		"vision",
		"horoscope",
		"saga",
		"tale",
        "mansion",
        "labrynth",
		"magic",
		"carnival",
        "dawn",
		"diamonds",
		"whispers",
		"invasion",
        "eclipse",
        "harvest",
		"prince",
		"constellation",
		"king",
		"emperor",
		"queen",
        "gold",
		"quest",
		"pact",
		"bargain",
        "shadow",
        "treasure",
		"village",
		"touch",
		"sacrifice",
        "bride",
        "war",
        "tales"
    ],

    "substance": [
        "blood",
        "slime",
        "ooze",
        "tears",
		"goo",
        "ichor"
    ],

    "job": [
        "commando",
        "soldier", 
        "legion",
        "barbarian",
		"commander",
		"master",
		"dr.",
		"mr.",
		"mrs.",
		"professor",
		"samurai",
		"geisha",
		"holy man",
		"priest",
		"librarian",
		"occultist",
		"avenger",
		"servant",
		"night",
		"witch",
		"prince",
		"legionnaire",
		"crusader",
		"alchemist",
		"secret agent",
        "destroyer",
        "conqueror",
		"raider",
		"trooper",
		"pirate",
        "rider",
        "raider",
        "astronaut",
        "cop"
    ],

	"threat": [
		"alien",
		"amoeba",
		"anaconda",
		"angel",
		"ant",
		"astronaut",
		"barbarian",
		"bat",
		"bear",
		"beast",
		"bee",
		"being",
		"bigfoot",
		"biker",
		"bird",
		"blob",
		"brain",
		"bunny",
		"water",
		"wind",
		"bureaucracy",
		"butcher",
		"cannibal",
		"car",
		"cat",
		"cheetah",
		"chicken",
		"child",
		"chimera",
		"chupacabra",
		"claw",
		"cloud",
		"clown",
		"cockatrice",
		"color",
		"comet",
		"computer",
		"consciousness",
		"cop",
		"corpse",
		"creature",
		"creep",
		"cube",
		"cultist",
		"cyborg",
		"demon",
		"dinosaur",
		"dog",
		"doll",
		"dracula",
		"dragon",
		"duke",
		"duplicator",
		"eagle",
		"element",
		"elf",
		"eye",
		"fairy",
		"finger",
		"fire",
		"fish",
		"frog",
		"fruit",
		"gargoyle",
		"ghost",
		"ghoul",
		"giant",
		"girl",
		"gnome",
		"goblin",
		"god",
		"goddess",
		"gorgon",
		"gremlin",
		"hand",
		"harlot",
		"heart",
		"hobgoblin",
		"hunger",
		"hydra",
		"imp",
		"inferno",
		"invader",
		"it",
		"knight",
		"kobold",
		"kraken",
		"laser",
		"leech",
		"leprechaun",
		"leviathan",
		"lich",
		"lizard",
		"lord",
		"lurker",
		"maggot",
		"maniac",
		"mantis",
		"maw",
		"menace",
		"mermaid",
		"merman",
		"mind",
		"mist",
		"mole",
		"monolith",
		"monster",
		"mouth",
		"mummy",
		"mutant",
		"native",
		"ninja",
		"pain",
		"piranha",
		"pirate",
		"plane",
		"plant",
		"poltergeist",
		"puma",
		"puppet",
		"python",
		"rabbit",
		"razor",
		"robot",
		"santa claus",
		"sasquatch",
		"satan",
		"satyr",
		"saucer",
		"scorpion",
		"seaweed",
		"seer",
		"serpent",
		"sex magick",
		"shadow",
		"shark",
		"shattered",
		"ship",
		"siren",
		"skull",
		"slime",
		"snake",
		"snatcher",
		"sorceror",
		"soul",
		"spectre",
		"sphere",
		"spider",
		"spirit",
		"stalker",
		"starship",
		"statue",
		"stomach",
		"tendril",
		"tentacle",
		"termite",
		"terror",
		"thing",
		"threat",
		"tiger",
		"tofu",
		"tornado",
		"toy",
		"troll",
		"turtle",
		"typhoon",
		"ufo",
		"unamerican activity",
		"undead",
		"unicorn",
		"urge",
		"vampire",
		"vapor",
		"fever",
		"madness",
		"vine",
		"wasp",
		"werewolf",
		"witch",
		"wizard",
		"woman",
		"yeti",
		"zombie"
	],

	"place": [
			"another dimension",
			"another world",
			"below",
			"beyond",
			"beyond the grave",
			"#adj# town",
			"Egypt",
			"the nile",
			"mesoptamia",
			"the frozen north",
			"#adj# ville",
			"prison",
			"jail",
			"beyond the stars",
			"the #adj# room",
			"the #maybe_adj# jungle",
			"the solar system",
			"the moon",
			"another galaxy",
			"another universe",
			"titan",
			"the fields",
			"the #maybe_adj# underworld",
			"the attic",
			"the basement",
			"the #maybe_adj# mine",
			"the #maybe_adj# lake",
			"phobos",
			"hades",
			"before time",
			"Omicron Persei 8",
			"hell",
			"io",
			"the #maybe_adj# tower",
			"mars",
			"mercury",
			"neptune",
			"#maybe_adj# space",
			"pluto",
			"saturn",
			"uranus",
			"venus",
			"inside the walls",
			"the deep",
			"atlantis",
			"tampa",
			"main street USA",
			"soviet russia",
			"the center of the earth",
			"the #maybe_adj# lagoon",
			"under the earth",
			"under the sea",
			"beyond time",
			"the far east",
			"the #maybe_adj# continent",
			"the future",
			"20,000 fathoms",
			"the ocean",
			"the wilderness",
			"planet x",
			"beyond the #maybe_adj# barrier",
			"The #maybe_adj# swamp",
			"L.A.",
			"bavaria",
			"The Himalayas",
			"Tibet",
			"New Jersey",
			"the Orient",
			"Babylonia",
			"the suburbs",
			"the #maybe_adj# sands",
			"the #maybe_adj# shores",
			"the #maybe_adj# zone",
			"yucca flats",
			"the year 5000",
			"the #maybe_adj# kingdom",
			"beyond the #maybe_adj# rim",
			"the #maybe_adj# hill",
			"the #maybe_adj# hills",
			"#maybe_adj# mountain",
			"the north pole",
			"Antarctica",
			"the #maybe_adj# mountains"
	],

	"maybe_adj": [
		"",
		"#adj#"
	],

	"adj": [
		"star",
		"abominable",
		"infernal",
		"accursed",
		"adult",
		"phantom",
		"phantasm",
		"surfing", 
		"invisible",
		"aggressive",
		"micro",
		"atomic",
		"aztec",
		"space",
		"dark",
		"hollow",
		"albino",
		"toxic",
		"alien",
		"demolished",
		"amorphous",
		"ancient",
		"bubble",
		"mutated",
		"chimeric",
		"long-lost",
		"abandoned",
		"occult",
		"deranged",
		"backwoods",
		"christian",
		"satanic",
		"black",
		"bloody",
		"teenage",
		"melting",
		"demonic",
		"fantastic",
		"sinister",
		"final",
		"amazing",
		"mighty",
		"blood-soaked",
		"blood-sucking",
		"violent",
		"carnal",
		"astro",
		"rocket",
		"space age",
		"chainsaw",
		"charnel",
		"reanimated",
		"cosmic",
		"solar",
		"corrupt",
		"depraved",
		"colossal",
		"crawling",
		"time",
		"cyclopean",
		"dead",
		"deadly",
		"stellar",
		"devastating",
		"deviant",
		"magic",
		"million",
		"dirty",
		"outer",
		"diseased",
		"dread",
		"eldrich",
		"endless",
		"eternal",
		"evil",
		"ferocious",
		"fetid",
		"flesh-eating",
		"radioactive",
		"fleshy",
		"forbidden",
		"foul-mouthed",
		"freakish",
		"freaky",
		"fungal",
		"ghost",
		"ghostly",
		"gelatinous",
		"giant",
		"gibbous",
		"gloaming",
		"glorious",
		"green",
		"grim",
		"groaning",
		"heathen",
		"hedonistic",
		"hoary",
		"indestructible",
		"she-",
		"horrendous",
		"horrifying",
		"terrible",
		"inhuman",
		"infinite",
		"indescribable",
		"jungle",
		"killer",
		"living",
		"lost",
		"lurking",
		"macabre",
		"mad",
		"man-eating",
		"medieval",
		"mysterious",
		"mystical",
		"neanderthal",
		"nocturnal",
		"nuclear",
		"one-eyed",
		"obsidian",
		"ophidian",
		"prehistoric",
		"primal",
		"primeval",
		"rabid",
		"raunchy",
		"red",
		"haunted",
		"remorseless",
		"robo-",
		"sentient",
		"shadowy",
		"skeletal",
		"spooky",
		"titanic",
		"neon",
		"insidious",
		"temporal",
		"photonic",
		"stygian",
		"communist",
		"soviet",
		"polyamorous",
		"subterranean",
		"supernatural",
		"telepathic",
		"tenebrous",
		"laughing",
		"octo-",
		"hexa-",
		"hexed",
		"vedic",
		"terrifying",
		"timeless",
		"crystal",
		"toxic",
		"transdimensional",
		"transparent",
		"undead",
		"untamed",
		"unstoppable",
		"vampiric", 
		"wild",
		"lecherous",
		"shrinking",
		"incredible",
		"woodland"
	]
}


grammar = tracery.Grammar(RULES)
grammar.add_modifiers(base_english)
for i in range(1000):
    print(grammar.flatten("#origin#"))
