import tracery
from tracery.modifiers import base_english

# restore
#"sex magick",
#],
#named threats (don't want 'the' ahead of them
#	"gods" : [
#		"ra",
#		"satan",
#		"hades",
#		"oberon",
#		"ra",
#		"isis"
#	],


RULES = {

	# "library"
	"roman_numeral": ["I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X", ],
	"number": [ "2", "3", "4", "5", "6", "II", "III", "IV", "V", "VI", "VII", ],
	"color": ["red", "green", "black", "white", "blue", "brown", "orange", "yellow", "obsidian", "ivory", "ebon", "ebony"],
	"sexy_material": ["leather", "lace", "pvc", "latex", "lingerie"],
	"title": [ "dr.", "mr.", "mrs.", "professor",],
	"magic_type": ["", "sex", "#color#", "dark", "evil", "nature"],
	"letter": [ "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"],

	"evil_group": [
		"communist party",
		"illuminati",
		"secret society",
		"cabal",
		"unamerican activity",
		"lizard people",
		"mafia",
		"vatican",
		"inner circle",
		"secret service",
		"CIA",
		"FBI",
		"KGB",
		"congress",
		"SS",
	],

	"battle": [
        "attack",
        "revenge",
		"battle",
		"revolution",
		"upheaval",
		"hunt",
		"battlefield",
		"bloodbath",
		"mutiny",
		"invasion",
        "war",
        "massacre",
		"holocaust",
	],


	# Maybes
	"adverb": [ "of", "in", "came from", "from", "before", "corrupted by", "from beyond", "inside", "above", "within"],
	"maybe_adj": [ "", "#adj#"],
	"maybe_roman_numeral": [ "", "#roman_numeral#"],

    "shortform": ["#threat#"],
    "shortpluralform": ["#threat.s#"],
	"possessive_form": ["#threat#'s"],

    "form": [ "#maybe_adj# #shortform#", ],
    "pluralform": [ "#maybe_adj# #shortpluralform#", ],

    "origin": [
		# unsorted:
        "#body_part# #shortform#",
        "#object# of the #form#",
        "#shortform# #object#",
        "The #body_part# of the #shortform#",
		"#adj# #job#: The #object# of the #form#",
		"#adj# #object#",
		"#adj# #object# of the #pluralform#",

		# basic form
        "#form#!",
        "The #form#",
		"#silly_prefix# #form#",
		"#form# #silly_suffix#",
		"The #adj# #adj# #shortform#",
		"The #form# that came from #place#",
		
		# battles
        "#form# VS. #form#",
        "The #form# and the #form#",
        "#shortform#-zilla VS #shortform#-ra",

		# job
		"#form# #job#",
		"#title# #job#",
        "#job# #shortform# and the #form# #adverb# #place#",
        "#job# #shortform# and the #shortform# #adverb# #place#",
        "#job# #adverb# #place#",

		# The Sword of the lictor
        "The #object# of the #pluralform#",

		# Vampire hunter D
		"#shortform# #job# #letter#",

		# The masque of the red death
		"The #object# of the #adj# #object#",

		# Ilsa: she wolf of the ss
		"#form#: #threat# of the #evil_group#",

		# Shadow over innsmouth
		"The #object# #adverb# #place#",

		# "star wars"
		"#adj# #battle#",

		# "grind-house"
		"#adj# #dwelling_place#",

		# escape from NY
		"escape from #place#", 

		# the day of the triffids
		# the night of the lepus
		"The #moment_in_time# of the #pluralform#",

		# The blood on satan's claw
		"The #threatening_substance# on the #possessive_form# #body_part#",

		# Beyond the valley of the dolls
        "Beyond the #spooky_locale# of the #pluralform#",
		
		# sky captain and the world of tomorrow
		"#form# and the world of #time#",


		# form from place
        "The #form# #adverb# #place#",
        "The #shortform# #adverb# #place#",
		"#pluralform# #adverb# #place#",
		"#pluralform#: beyond #place#",

		# forms I want to appear more rarely
		"#sexploitation_title#",
        "#iconic_structure#",
		"#silly_sequels#",
    ],

	"silly_sequels" : [
		"#place# #number#: The #form#",
		"#place# #number#: Return of the #form#",
		"#place# #number#: #form# #object#",
		"#place# #number#: #object# of the #form#",
		"#form# #number#: #adverb# #place#",
		"The #form# #number#: #adverb# #place#",
	],

	"sexploitation_title" : [
        "#form# de Sade",
        "Sex Slaves of the #form#",
        "The Loves of the #form#",
        "Sexy #threat.s# in Cages",
        "The #form# Lovers",
        "#form# in #sexy_material#",
        "#pluralform# in #sexy_material#",
	],

	"iconic_structure" : [
        "#shortform#-Geddon",
        "#shortform#-nado",
        "#shortform#-zilla",
        "I Walked with #pluralform#",
		"The #form# that Wouldn't Die#",
		"The #form# that Couldn't be Killed",
        "30 #shortform.s#, 30 Days",
        "30 #shortform.s# in 30 Days",
	],

	"silly_suffix": [
		"! kill! kill!",
		": The revenge",
		": The return",
		": #space_age# #ritual#",
		": #story# of the #threat#",
	],

	"silly_prefix": [
		"Code Name:",
		"Alias:",
		"Danger!!",
		"The Wild Wild World of the",
        "Death by",
        "I Married a",
		"Fear the",
		"Dread the",
        "I Walked with the",
        "I Became a",
        "My Wife is a",
        "I Was a Teenage",
	],

	"story": [
        "legend",
		"secret",
		"fable",
		"fate",
		"saga",
		"tale",
		"tales",
	],

	"moment_in_time": [
        "day",
        "night",
		"year",
		"solstice",
		"time",
        "dawn",
		"rise",
		"dusk",
	],


	# religious rite
	"ritual": [
		"#color# mass",
		"ball",
		"boogaloo",
		"dance",
		"festival",
		"funeral",
		"mass",
		"opera",
		"orgy",
		"party",
		"pyre",
		"rite",
		"ritual",
		"sacrifce",
	],

    "object": [
		# TODO: Move some space stuff back here?
		"#dwelling_place#",
		"#spooky_locale#",
		"#body_part#",
		"#story#",
		"#job#",
		"#battle#",
		"#moment_in_time#",
		"#ritual#",
		
		# unsorted
		"planet",
		"escape", 
		"dream",
        "vigil",
        "horror",
		"domain",
		"million eyes", 
        "death",
		"madness",
		"laugh",

		#thoughts
		"betrayal",
		"lies",
		"promises",
		"wishes",

		#sounds
		"scream",
		"song",
		"sound",
		"melody",

		# inspiration
        "call",
		"quest",
		"adventure",
		"journey",

		# systems of government / groups
		"anarchy",
		"alliance",
		"cult",
		"monarchy",
		"fellowship",
		"reign",
		"empire",

		# object / weapon / tool
		"sword",
		"gun",
		"hammer",
		"mace",
		"plate",
		"armor",
		"drill",
		"shovel",
		"shield",
		"lance",
        "mask", 
		"masque",
		"key",
		"crystal ball",
		"ring",
		"rings",
	
		# magical stuff
		"#magic_type# magic",
		"#magic_type# magick",
		"#magic_type# tome",
		"#magic_type# spellbook",

		# riches
		"diamonds",
        "harvest",
        "gold",
        "treasure",

		# spooky evidence
		"vision",
		"visions",
		"stare",
		"tracks",
		"sign",
		"remnant",
		"footprints",
		"fossil",
        "shadow",
		"touch",
		"sacrifice",
		"whispers",
		"echoes",
		"stench",
		"shard",
		"bone",
		"ruin",
		"trail",

		# scheme
		"grudge",
		"plan",
		"plot",
        "revenge",
		"embrace",
		"conspiracy",
		"pact",
		"bargain",
		"deal",

		# partner
        "bride",
		"mate",

    ],

	"body_part": [
		"blood",
		"bone",
		"brain",
		"claw",
		"eye",
		"finger",
		"flesh",
		"foot",
		"gut",
		"hand",
		"heart",
		"jaw",
		"maw",
		"mind",
		"mouth",
		"muscle",
		"organ",
		"sinew",
		"skull",
		"spine",
		"stomach",
		"tendon",
		"tendril",
		"tentacle",
    ],

    "job": [
		"alchemist",
		"architect",
		"avenger",
		"baron",
		"biker",
		"boss",
		"butcher",
		"cannibal",
		"clown",
		"commander",
		"commando",
		"cop",
		"crusader",
		"cultist",
		"defender",
		"detective",
		"diver",
		"duke",
		"duplicator",
		"earl",
		"emperor",
		"empress",
		"football player",
		"geisha",
		"gladiator",
		"goddess",
		"groupie",
		"harlot",
		"holy man",
		"hunter",
		"invader",
		"king",
		"knight",
		"legionnaire",
		"librarian",
		"lord",
		"master",
		"night",
		"ninja",
		"occultist",
		"pirate",
		"priest",
		"prince",
		"princess",
		"private eye",
		"professor",
		"queen",
		"raider",
		"samurai",
		"scientist",
		"secret agent",
		"seer",
		"servant",
		"slayer",
		"snatcher",
		"sorceror",
		"trooper",
		"witch",
		"wizard",
        "astronaut",
        "barbarian",
        "commando",
        "conqueror",
        "cop",
        "destroyer",
        "judge",
        "legion",
        "raider",
        "rider",
        "soldier", 
		"villager",
    ],

	"food": [
		"fruit",
		"water",
		"mushroom",
		"casserole",
		"egg", 
		"tofu",
	],

    "real_animal": [
		"amoeba",
		"virus",
		"bacteria",
		"anaconda",
		"ant",
		"bat",
		"bear",
		"bee",
		"bird",
		"bunny",
		"cat",
		"cheetah",
		"chicken",
		"dinosaur",
		"dog",
		"eagle",
		"fish",
		"frog",
		"leech",
		"lizard",
		"maggot",
		"mantis",
		"mole",
		"piranha",
		"plant",
		"puma",
		"python",
		"rabbit",
		"raven",
		"scorpion",
		"seaweed",
		"serpent",
		"shark",
		"snake",
		"spider",
		"termite",
		"tiger",
		"turtle",
		"vine",
		"vulture",
		"wasp",
		"worm",
    ],

	"natural_phenomena": [
		"cloud",
		"comet",
		"fire",
		"flood",
		"hurricane",
		"inferno",
		"mist",
		"pool",
		"sandstorm",
		"shadow",
		"tornado",
		"typhoon",
		"vapor",
		"water",
		"wind",
    ],

    "shapes": [
		"color",
		"element",
		"colour",
		"blob",
		"cube",
		"form",
		"monolith",
		"sphere",
    ],

    "technology": [
		"android",
		"blade",
		"car",
		"computer",
		"doll",
		"elevator",
		"factory",
		"gear",
		"hologram",
		"laser",
		"machine",
		"mystereon",
		"plane",
		"puppet",
		"robot",
		"rocket",
		"saucer",
		"ship",
		"spaceship",
		"starship",
		"statue",
		"toy",
		"truck",
		"tunnel",
		"ufo",
        "automaton",
    ],

    "fantasy_animal": [
		"alien",
		"angel",
		"bigfoot",
		"chimera",
		"chupacabra",
		"cockatrice",
		"cyborg",
		"demon",
		"dracula",
		"dragon",
		"elf",
		"fairy",
		"gargoyle",
		"ghost",
		"ghoul",
		"giant",
		"gnome",
		"goblin",
		"god",
		"golem",
		"gorgon",
		"gremlin",
		"hobgoblin",
		"homunculus",
		"hydra",
		"imp",
		"kobold",
		"kraken",
		"leprechaun",
		"lepus"
		"leviathan",
		"lich",
		"lictor",
		"lycanthrope",
		"mermaid",
		"merman",
		"monster",
		"mummy",
		"mutant",
		"ogre",
		"phoenix",
		"poltergeist",
		"santa claus",
		"sasquatch",
		"satyr",
		"shapeshifter",
		"siren",
		"soul",
		"spectre",
		"spirit",
		"stalker",
		"troll",
		"undead",
		"unicorn",
		"vampire",
		"werewolf",
		"wight",
		"yeti",
		"zombie",
    ],

	"societal": [
		"bureaucrat",
		"communist",
		"taxman",
		"president",
		"czar",
	],

	"humans": [
		"man",
		"woman",
		"teenager",
	],

	"women": [
		"girl",
		"bimbo",
		"woman",
		"cheerleader",
	],

	"threatening_thing": [
		"creep",
		"beast",
		"terror",
		"creature",
		"it",
		"thing",
		"threat",
		"lurker",
		"being",
		"maniac",
		"menace",
		"corpse",
	],

	"scary_phenomena" : [
		"hunger",
		"urge",
		"fever",
		"consciousness",
		"nausea",
		"pain",
		"madness",
		"anguish",
	],

	"threatening_substance" : [
		"blood",
		"slime",
		"ooze",
		"goop",
		"sludge",
		"mess",
		"goo",
		"ichor",
	],

	"threat": [
        "#real_animal#",
        "#fantasy_animal#",
        "#job#",
        "#body_part#",
        "#technology#",
		"#natural_phenomena#",
		"#food#",
		"#women#",
		"#societal#",
		"#humans#",
		"#threatening_thing#",
		"#scary_phenomena#",
		"#threatening_substance#",
		#"#gods#",
	],

	"menacing_places_on_earth": [
		"Egypt",
		"the nile",
		"mesoptamia",
		"tampa",
		"the frozen north",
		"main street USA",
		"soviet russia",
		"L.A.",
		"Basque Country",
		"Bavaria",
		"The pacific",
		"the atlantic",
		"The Himalayas",
		"Tibet",
		"New Jersey",
		"yucca flats",
		"the north pole",
		"Antarctica",
		"the far east",
		"the Orient",
		"Babylonia",
		"the center of the earth",
	],

	"scary_parts_of_a_house" : [
		"sewer",
		"kitchen",
		"walls",
		"attic",
		"basement",
		"cellar",
		"fireplace",
		"room",
		"shed out back",
		"well",
		"bed",
		"floorboards",
		"stairs",
	],

	"space_places" : [
		"space", 
        "eclipse",
		"constellation",

		"phobos",
		"io",
		"the moon",
		"mars",
		"mercury",
		"the astroid belt",
		"sol",
		"neptune",
		"jupiter",
		"pluto",
		"saturn",
		"titan",
		"uranus",
		"venus",
		"planet x",

		"another galaxy",
		"another universe",
		"another dimension",
		"another world",
		"the stars",
		"the solar system",
		
		# stars or planets around them
		"altair #maybe_roman_numeral#",
		"Andromeda #maybe_roman_numeral#",
		"cygnus #maybe_roman_numeral#",
		"pegasus #maybe_roman_numeral#",
		"orion #maybe_roman_numeral#",
		"corona borealis #maybe_roman_numeral#",
		"cetus #maybe_roman_numeral#",
	],
	
	"unpleasant_places" : [
		"prison",
		"jail",
		"the suburbs",
		"the fair",
		"the mall",
		"the science fair",
		"the carnival",
		"the DMV",
	],

	"mythological_places" : [
		"hell",
		"atlantis",
		"valhalla",
		"underworld",
		"plane of leng",
		"miskatonic university",
		"Innsmouth"
		"hades",
		"avalon",
		"Shangra La",
		"El Dorado",
		"carcosa",
		"Omicron Persei 8",
		"vulcan",
	],

	"spooky_locale_without_the": [
		"swamp", 
		"island", 
		"lake", 
		"tower",
		"mountain",
		"hill",
	],

	"spooky_locale": [
		"barren",
		"barrier",
		"caldera",
		"carnival",
		"castle",
		"cave",
		"continent",
		"crater",
		"crypt",
		"dungeon",
		"field",
		"forest",
		"grave",
		"grotto",
		"hill",
		"hive",
		"island",
		"jungle",
		"keep",
		"kingdom",
		"lagoon",
		"lagoon", 
		"lake",
		"mausoleum",
		"mine",
		"mountain",
		"rim",
		"ruin",
		"sands",
		"sepulcher",
		"shores",
		"swamp",
		"throne",
		"tomb",
		"torture chamber",
		"tower",
		"valley"
		"vault",
		"volcano",
		"wilderness",
        "fortress",
        "labrynth",
        "pit",
	],

	"water_and_oceans" :[
		"the sea",
		"the deep",
		"20,000 fathoms",
		"the ocean",
		"the reef",
		"the trench",
	],

	"dwelling_place" : [
		"village",
        "hotel",
        "house",
		"mansion",
		"fort",
		"town",
		"colony",
		"city",
		"realm",
		"zone",
		"-ville",
	],

	"religious_buildings" : [
		"church",
		"the cathedral",
		"the pagoda",
		"the chapel",
		"the reliquary",
		"synagogue",
		"the mosque",
		"temple",
	],

	"time" : [
		"time",
		"the future",
		"tomorrow",
		"the year 2000",
		"the year 5000",
		"the year 10000",
		"the 41st Millennium",
	],

	"place": [
		"below",
		"beyond",
		"the earth",
		"#menacing_places_on_earth#",	
		"the #maybe_adj# #scary_parts_of_a_house#",
		"#unpleasant_places#",
		"#space_places#",
		"#mythological_places#",
		"#water_and_oceans#",
		"#religious_buildings#",
		"the #maybe_adj# #spooky_locale#",
		"#adj# #spooky_locale_without_the#",
		"#adj# #dwelling_place#",
		"#time#",
	],

	##################### Adjectives #######################

	"material" : [
		"iron",
		"metal",
		"crystal",
		"bone",
		"wooden",
		"hollow",
		"glowing",
	],

	"sexploitation": [
		"kinky",
		"BDSM",
		"promiscuous",
		"raunchy",
		"dirty",
		"hedonistic",
		"desperate",
		"pent-up",
		"carnal",
		"freaky",
		"deviant",
		"fleshy",
		"sexy",
		"lavacious",
		"adult",
		"lecherous",
		"leather",
	],

	"old" : [
		"eldrich",
		"prehistoric",
		"medieval",
		"long-lost",
		"lost",
		"primal",
		"primeval",
		"forgotten",
		"cyclopean",
		"ancient",
		"abandoned",
	],

	"nuclear_science_y" : [
		"nuclear",
		"atomic",
		"radioactive",
		"toxic",
		"mutated",
	],

	"magical": [
		"hexed",
		"accursed",
		"magic",
		"magical",
		"supernatural",
		"telepathic",
		"voodoo",
		"telekinetic",
		"vedic",
		"sorcerous",
		"cursed",
		"forbidden",
		"mysterious",
		"ghost",
		"ghostly",
	],

	"space_age" : [
		"robo-",
		"astro",
		"rocket",
		"solar",
		"neon",
		"space",
		"mecha-",
		"mechano-",
		"techno-",
		"electric",
		"electro-mechanical",
		"cybernetic",
		"stellar",
		"turbo",
		"uber",
		"photonic",
		"temporal",
		"holographic",
		"time",
		"transdimensional",
		"ultra",
		"futuristic",
		"techno",
		"space age",
	],

	"decayed" : [
		"demolished",
		"diseased",
		"one-eyed",
		"disgusting",
		"melting",
		"bubbling",
		"rotting",
		"putrid",
		"fetid",
	],
	
	# violent / crazy / dangerous / evil
	"evil" : [
		"abominable",
		"aggressive",
		"corrupt",
		"dark",
		"deadly",
		"demonic",
		"depraved",
		"deranged",
		"dread",
		"evil",
		"ferocious",
		"godless",
		"grim",
		"haunted",
		"horrendous",
		"horrifying",
		"infernal",
		"inhuman",
		"insane",
		"insidious",
		"killer",
		"laughing",
		"lurking",
		"macabre",
		"mad",
		"remorseless",
		"satanic",
		"shadowy",
		"sinister",
		"skeletal",
		"spooky",
		"terrifying",
		"unstoppable",
		"vampiric", 
		"violent",
        "mindless",
	],

	"natural" : [
		"sentient",
		"gelatinous",
		"protoplasmic",
		"amorphous",
		"chimeric",
		"albino",
		"dead",
		"flesh-eating",
		"rabid",
		"nocturnal",
		"man-eating",
		"starving",
		"untamed",
		"wild",
		"living",
		"woodland",
		"backwoods",
		"blood-sucking",
		"fungal",
		"jungle",
	],

	"cosmic" :[
		"crawling",
		"alien",
		"indescribable",
		"endless",
		"infinite",
		"outer",
		"eternal",
		"occult",
		"cosmic",
		"final",
		"star",
		"timeless",
		"tenebrous",
		"gibbous",
		"gloaming",
		"groaning",
		"hoary",
		"stygian",
	],

	"wonderous" : [
		"glorious",
		"mystical",
		"incredible",
		"terrible",
		"awesome",
		"fantastic",
		"amazing",
	],

	"horror_movie" : [
		"blood-soaked",
		"charnel",
		"grind-",
		"chainsaw",
		"bloody",
		"gore-encrusted",
	],

	"size_related": [
		"micro",
		"shrinking",
		"giant",
		"colossal",
		"titanic",
		"enormous",
		"indestructible",
		"mighty",
	],

	"undead" : [
		"undead",
		"reborn",
		"reanimated",
	],

	# of a (mythological) earth civilization
	"religion_or_culture" : [
		"Aztec",
		"Egyptian",
		"christian",
		"jewish",
		"Mormon",
		"neanderthal",
		"heathen",
		"shamanistic",
		"Norse",
		"soviet",
		"communist",
	],

	"unseen": [
		"invisible",
		"immaterial",
		"empty",
		"phantasm",
		"phantom",
		"subterranean",
		"transparent",
	],

	"adj": [
		"#color#",
		"#material#",
		"#sexploitation#",
		"#old#",
		"#nuclear_science_y#",
		"#magical#",
		"#space_age#",
		"#decayed#",
		"#evil#",
		"#natural#",
		"#cosmic#",
		"#wonderous#",
		"#horror_movie#",
		"#size_related#",
		"#undead#",
		"#religion_or_culture#",
		"#unseen#",

		# a bit silly
		"teenage",
		"harsh",
		"surfing", 

	]
}


grammar = tracery.Grammar(RULES)
grammar.add_modifiers(base_english)
for i in range(100):
	title = grammar.flatten("#origin#")
	title = title.replace("womans", "women")
	title = title.replace(" mans ", " men ")
	title = title.replace("elfs", "elves")
	title = title.replace("nauseas", "nausea")
	title = title.replace("  ", " ")
	title = title.replace(" : ", ": ")
	print(title.strip().title())
