import tracery
from tracery.modifiers import base_english


# restore
#"sex magick",
#"title": [
#	"dr.",
#	"mr.",
#	"mrs.",
#],


RULES = {

	# "library"
	"roman_numeral": ["I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X", ],
	"number": [ "2", "3", "4", "5", "6", "II", "III", "IV", "V", "VI", "VII", ],
	"color": ["red", "green", "black", "white", "blue", "brown", "orange", "yellow"],
	"sexy_material": ["leather", "lace", "pvc", "latex", "oil"],

	# Maybes
	"maybe_beyond": [ "of", "from", "from beyond"],
	"maybe_adj": [ "", "#adj#"],
	"maybe_roman_numeral": [ "", "#roman_numeral#"],

    "shortform": ["#threat#"],
    "shortpluralform": ["#threat.s#"],

    "form": [ "#maybe_adj# #shortform#", ],
    "pluralform": [ "#maybe_adj# #shortpluralform#", ],


    "origin": [
		# unsorted:
		"#silly_prefix# #form#",
        "#body_part# #shortform#",
        "#object# of the #form#",
        "#shortform# #object#",
        "The #body_part# of the #shortform#",
		"#adj# #job#: The #object# of the #form#",
		"#adj# #object#",
		"The #adj# #adj# #shortform#",
        "I Walked with #pluralform#",
		"The #form# that Wouldn't Die#",
		"The #form# that Couldn't be Killed",

		# basic form
        "#form#!",
        "The #form#",
        "#shortform#-Geddon",
        "#shortform#-nado",
        "#shortform#-zilla",
		
		# battles
        "#form# VS. #form#",
        "The #form# and the #form#",
        "#shortform#-zilla VS #shortform#-ra",

		# job
        "#shortform# #job#",
        "#job# #shortform# and the #form# #after_place#",
        "#job# #shortform# and the #shortform# #after_place#",
        "#job# #after_place#",

		# form in days
        "30 #shortform.s#, 30 Days",
        "30 #shortform.s# in 30 Days",
		"Around #before_place# in 80 Days",

		# object of form
        "The #object# of #pluralform#",
        "The #object# of the #pluralform#",

		# form from place
        "The #form# #after_place#",
        "The #shortform# #after_place#",
        "#pluralform# #after_place#",

        # Silly sequels
		"#before_place# #number#: The #form#",
		"#before_place# #number#: Return of the #form#",
		"#before_place# #number#: #form# #object#",
		"#before_place# #number#: #object# of the #form#",
		"#form# #number#: #after_place#",
		"The #form# #number#: #after_place#",

        # Sexploitation!
        "#form# de Sade",
        "Sex Slaves of the #form#",
        "The Loves of the #form#",
        "Sexy #threat.s# in Cages",
        "The #form# Lovers",
        "#form# in Leather",
        "#form# in Lace",
        "#pluralform# in #sexy_material#",
        "Beyond the Valley of the #pluralform#",
    ],

	"silly_prefix": [
		"Code Name:",
		"Danger!!",
		"The Wild Wild World of the",
        "Death by",
        "I Married a",
		"Fear the",
		"Dread the",
        "I Walked with the",
        "I Became a",
        "My Wife is a",
        "I Was a Teenage",
	],

    "object": [
		# TODO: Move some space stuff back here?
		"#dwelling_place#",
		"#spooky_locale#",
		"#body_part#",
		"#job#",
		
		# unsorted
		"planet",
		"escape", 
		"dream",
        "vigil",
        "horror",
		"domain",
		"the million eyes", 
        "death",
		"madness",
		"laugh",

		#battle
        "attack",
        "revenge",
		"battle",
		"hunt",
		"battlefield",
		"bloodbath",
		"mutiny",
		"invasion",
        "war",
        "massacre",
		"holocaust",

		#thoughts
		"betrayal",
		"lies",
		"promises",
		"wishes",

		#sounds
		"scream",
		"song",
		"sound",
		"melody",

		# inspiration
        "call",
		"quest",
		"adventure",
		"journey",

		# history / story
        "legend",
		"fable",
		"fate",
		"saga",
		"tale",
		"tales",

		# moment in time / times of day
        "day",
        "night",
		"time",
        "dawn",
		"dusk",

		# systems of government / groups
		"alliance",
		"cult",
		"monarchy",
		"fellowship",
		"reign",
		"empire",

		# object / weapon
		"sword",
		"gun",
        "mask", 
		"key",
		"crystal ball",
		"ring",
		"rings",
	
		# magical stuff
		"magic",
		"tome",
		"obsidian",
		"spellbook",

		# riches
		"diamonds",
        "harvest",
        "gold",
        "treasure",

		# spooky evidence
		"vision",
		"visions",
		"stare",
		"tracks",
		"sign",
		"remnant",
		"footprints",
		"fossil",
        "shadow",
		"touch",
		"sacrifice",
		"whispers",
		"echoes",
		"stench",
		"shard",
		"bone",
		"ruin",
		"trail",

		# scheme
		"grudge",
		"plan",
		"plot",
        "revenge",
		"embrace",
		"conspiracy",
		"pact",
		"bargain",
		"deal",

		# partner
        "bride",
		"mate",

    ],

	"body_part": [
		"blood",
		"bone",
		"brain",
		"claw",
		"eye",
		"finger",
		"gut",
		"hand",
		"heart",
		"maw",
		"mind",
		"mouth",
		"organ",
		"skull",
		"spine",
		"stomach",
		"tendril",
		"tentacle",
    ],

    "job": [
		"alchemist",
		"architect",
		"avenger",
		"biker",
		"boss",
		"butcher",
		"cannibal",
		"clown",
		"commander",
		"cop",
		"crusader",
		"cultist",
		"defender",
		"duke",
		"duplicator",
		"empress",
		"emperor",
		"geisha",
		"gladiator",
		"goddess",
		"groupie",
		"harlot",
		"holy man",
		"invader",
		"king",
		"knight",
		"legionnaire",
		"librarian",
		"lord",
		"master",
		"native",
		"night",
		"ninja",
		"occultist",
		"pirate",
		"priest",
		"prince",
		"princess",
		"professor",
		"queen",
		"raider",
		"samurai",
		"secret agent",
		"seer",
		"servant",
		"snatcher",
		"sorceror",
		"trooper",
		"witch",
		"wizard",
        "astronaut",
        "barbarian",
        "commando",
        "conqueror",
        "cop",
        "destroyer",
        "judge",
        "legion",
        "raider",
        "rider",
        "soldier", 
    ],

	"food": [
		"fruit",
		"water",
		"bean",
		"mushroom",
		"egg", 
		"tofu",
	],

    "real_animal": [
		"amoeba",
		"virus",
		"bacteria",
		"anaconda",
		"ant",
		"bat",
		"bear",
		"bee",
		"bird",
		"bunny",
		"cat",
		"cheetah",
		"chicken",
		"dinosaur",
		"dog",
		"eagle",
		"fish",
		"frog",
		"leech",
		"lizard",
		"maggot",
		"mantis",
		"mole",
		"piranha",
		"plant",
		"puma",
		"python",
		"rabbit",
		"scorpion",
		"seaweed",
		"serpent",
		"shark",
		"snake",
		"spider",
		"termite",
		"tiger",
		"turtle",
		"vine",
		"vulture",
		"wasp",
    ],

	"natural_phenomena": [
		"typhoon",
		"hurricane",
		"flood",
		"sandstorm",
		"vapor",
		"pool",
		"shadow",
		"tornado",
		"fire",
		"cloud",
		"water",
		"wind",
		"comet",
		"inferno",
		"mist",
    ],

    "shapes": [
		"color",
		"element",
		"colour",
		"blob",
		"cube",
		"form",
		"monolith",
		"sphere",
    ],

    "technology": [
		"doll",
		"razor",
		"factory",
		"toy",
		"puppet",
		"plane",
		"ship",
		"car",
		"starship",
		"laser",
		"robot",
		"statue",
		"computer",
		"saucer",
		"ufo",
        "automaton",
    ],

    "fantasy_animal": [
		"alien",
		"angel",
		"bigfoot",
		"chimera",
		"chupacabra",
		"cockatrice",
		"cyborg",
		"demon",
		"dracula",
		"dragon",
		"elf",
		"fairy",
		"gargoyle",
		"ghost",
		"ghoul",
		"giant",
		"gnome",
		"goblin",
		"god",
		"golem",
		"gorgon",
		"gremlin",
		"hobgoblin",
		"homunculus",
		"hydra",
		"imp",
		"kobold",
		"kraken",
		"leprechaun",
		"leviathan",
		"lich",
		"lictor",
		"lycanthrope",
		"mermaid",
		"merman",
		"monster",
		"mummy",
		"mutant",
		"ogre",
		"phoenix",
		"poltergeist",
		"santa claus",
		"sasquatch",
		"satan",
		"satyr",
		"shapeshifter",
		"siren",
		"soul",
		"spectre",
		"spirit",
		"stalker",
		"troll",
		"undead",
		"unicorn",
		"vampire",
		"werewolf",
		"wight",
		"yeti",
		"zombie",
    ],

	"societal": [
		"bureaucrat",
		"communist",
		"unamerican activity",
		"orgy",
	],

	"humans": [
		"man",
		"woman",
		"child",
		"kid",
		"teenager",
	],

	"women": [
		"girl",
		"bimbo",
		"woman",
		"cheerleader",
	],

	"threatening_thing": [
		"creep",
		"beast",
		"terror",
		"creature",
		"it",
		"thing",
		"threat",
		"lurker",
		"being",
		"maniac",
		"menace",
		"corpse",
	],

	"scary_phenomena" : [
		"hunger",
		"urge",
		"fever",
		"consciousness",
		"pain",
		"madness",
		"nausea",
		"anguish",
	],

	"threatening_substance" : [
		"blood",
		"slime",
		"ooze",
		"tear",
		"goo",
		"ichor",
	],

	"threat": [
        "#real_animal#",
        "#fantasy_animal#",
        "#job#",
        "#body_part#",
        "#technology#",
		"#natural_phenomena#",
		"#food#",
		"#women#",
		"#societal#",
		"#humans#",
		"#threatening_thing#",
		"#scary_phenomena#",
		"#threatening_substance#",
	],

	"menacing_places_on_earth": [
		"Egypt",
		"the nile",
		"mesoptamia",
		"tampa",
		"the frozen north",
		"main street USA",
		"soviet russia",
		"L.A.",
		"bavaria",
		"The Himalayas",
		"Tibet",
		"New Jersey",
		"yucca flats",
		"the north pole",
		"Antarctica",
		"the far east",
		"the Orient",
		"Babylonia",
		"the center of the earth",
	],

	"scary_parts_of_a_house" : [
		"#maybe_adj# sewer",
		"in the #maybe_adj# kitchen",
		"inside the #maybe_adj# walls",
		"the #maybe_adj# attic",
		"the #maybe_adj# basement",
		"the #maybe_adj# cellar",
		"the #maybe_adj# fireplace",
		"the #maybe_adj# room",
		"the #maybe_adj# shed out back",
		"the #maybe_adj# well",
		"under the #maybe_adj# bed",
		"under the #maybe_adj# floorboards",
		"under the #maybe_adj# stairs",
	],

	"space_places" : [
		"space", 
        "eclipse",
		"constellation",

		"phobos",
		"io",
		"the moon",
		"mars",
		"mercury",
		"the astroid belt",
		"sol",
		"neptune",
		"jupiter",
		"pluto",
		"saturn",
		"titan",
		"uranus",
		"venus",
		"planet x",

		"another galaxy",
		"another universe",
		"another dimension",
		"another world",
		"the stars",
		"the solar system",
		
		# stars or planets around them
		"altair #maybe_roman_numeral#",
		"Andromeda #maybe_roman_numeral#",
		"cygnus #maybe_roman_numeral#",
		"pegasus #maybe_roman_numeral#",
		"orion #maybe_roman_numeral#",
		"corona borealis #maybe_roman_numeral#",
		"vela #maybe_roman_numeral#",
		"cetus #maybe_roman_numeral#",
	],
	
	"unpleasant_places" : [
		"prison",
		"jail",
		"the suburbs",
		"the fair",
		"the mall",
		"the science fair",
		"the carnival",
		"the DMV",
	],

	"mythological_places" : [
		"hell",
		"atlantis",
		"valhalla",
		"underworld",
		"hades",
		"avalon",
		"Shangra La",
		"El Dorado",
		"carcosa",
		"Omicron Persei 8",
		"vulcan",
	],

	"spooky_locale_without_the": [
		"swamp", 
		"island", 
		"lake", 
		"tower",
		"mountain",
		"hill",
	],

	"spooky_locale": [
		"barren",
		"barrier",
		"caldera",
		"carnival",
		"castle",
		"cave",
		"continent",
		"crater",
		"crypt",
		"dungeon",
		"field",
		"forest",
		"grave",
		"grotto",
		"hill",
		"hive",
		"island",
		"jungle",
		"keep",
		"kingdom",
		"lagoon",
		"lagoon", 
		"lake",
		"mausoleum",
		"mine",
		"mountain",
		"rim",
		"ruin",
		"sands",
		"sepulcher",
		"shores",
		"swamp",
		"throne",
		"tomb",
		"torture chamber",
		"tower",
		"vault",
		"volcano",
		"wilderness",
        "fortress",
        "labrynth",
        "pit",
	],

	"water_and_oceans" :[
		"under the sea",
		"the deep",
		"20,000 fathoms",
		"the ocean",
		"the reef",
		"the trench",
	],

	"dwelling_place" : [
		"village",
        "hotel",
        "house",
		"mansion",
		"condo",
		"fort",
		"town",
		"colony",
		"city",
		"realm",
		"zone",
		"ville",
	],

	"time" : [
		"before time",
		"beyond time",
		"the future",
		"the year 2000",
		"the year 5000",
		"the year 10000",
		"the 41st Millennium",
	],

	"before_place": [
		"below",
		"beyond",
		"under the earth",
		"#menacing_places_on_earth#",	
		"#scary_parts_of_a_house#",
		"#unpleasant_places#",
		"#space_places#",
		"#mythological_places#",
		"#water_and_oceans#",
		"the #maybe_adj# #spooky_locale#",
		"#adj# #spooky_locale_without_the#",
		"#adj# #dwelling_place#",
		"#time#",
	],

	"after_place": [
		"below",
		"beyond",
		"under the earth",
		"#menacing_places_on_earth#",	
		"#scary_parts_of_a_house#",
		"#unpleasant_places#",
		"#maybe_beyond# #space_places#",
		"#maybe_beyond# #mythological_places#",
		"#maybe_beyond# #water_and_oceans#",
		"#maybe_beyond# the #maybe_adj# #spooky_locale#",
		"#maybe_beyond# #adj# #spooky_locale_without_the#",
		"#adj# #dwelling_place#",
		"#time#",
	],

	"adj": [
		"#color#",

		# sexploitation-y
		"polyamorous",
		"promiscuous",
		"raunchy",
		"dirty",
		"hedonistic",
		"desperate",
		"pent-up",
		"carnal",
		"freaky",
		"deviant",
		"fleshy",
		"sexy",
		"lavacious",
		"adult",
		"lecherous",
		"leather",
	
		# old
		"eldrich",
		"prehistoric",
		"medieval",
		"long-lost",
		"lost",
		"primal",
		"primeval",
		"forgotten",
		"cyclopean",
		"ancient",
		"abandoned",

		# nuclear / science-y
		"nuclear",
		"atomic",
		"radioactive",
		"toxic",
		"mutated",

		# magical / other worldly
		"hexed",
		"accursed",
		"magic",
		"magical",
		"crystal",
		"iron",
		"supernatural",
		"telepathic",
		"telekinetic",
		"vedic",
		"sorcerous",
		"cursed",

		"forbidden",
		"mysterious",
		"ghost",
		"ghostly",

		# Space age / futuristic
		"robo-",
		"astro",
		"rocket",
		"solar",
		"neon",
		"space",
		"stellar",
		"turbo",
		"uber",
		"photonic",
		"temporal",
		"time",
		"transdimensional",
		"ultra",
		"futuristic",
		"techno",
		"space age",
	
		# decayed / disgusting
		"demolished",
		"diseased",
		"one-eyed",
		"disgusting",
		"melting",
		"bubbling",
		"rotting",
		"putrid",
		"fetid",

		# violent / crazy / dangerous / evil
		"sinister",
		"laughing",
		"insane",
		"killer",
		"inhuman",
		"infernal",
		"haunted",
		"ferocious",
		"godless",
		"demonic",
		"terrifying",
		"unstoppable",
		"horrendous",
		"horrifying",
        "mindless",
		"spooky",
		"skeletal",
		"sinister",
		"deadly",
		"evil",
		"freakish",
		"lurking",
		"vampiric", 
		"grim",
		"dread",
		"depraved",
		"dark",
		"deranged",
		"violent",
		"mad",
		"aggressive",
		"macabre",
		"abominable",
		"insidious",
		"satanic",
		"remorseless",
		"shadowy",
		"corrupt",

		# hungry / of the natural world
		"sentient",
		"gelatinous",
		"protoplasmic",
		"amorphous",
		"chimeric",
		"albino",
		"dead",
		"flesh-eating",
		"rabid",
		"nocturnal",
		"man-eating",
		"starving",
		"untamed",
		"wild",
		"living",
		"woodland",
		"backwoods",
		"blood-sucking",
		"fungal",
		"jungle",

		# cosmic horror / lovecraft
		"crawling",
		"alien",
		"indescribable",
		"endless",
		"infinite",
		"outer",
		"eternal",
		"occult",
		"cosmic",
		"final",
		"star",
		"timeless",
		"tenebrous",
		"gibbous",
		"gloaming",
		"groaning",
		"hoary",
		"stygian",

		# wonderous
		"glorious",
		"mystical",
		"incredible",
		"terrible",
		"awesome",
		"fantastic",
		"amazing",

		# horror movie
		"blood-soaked",
		"charnel",
		"chainsaw",
		"bloody",

		# small and big / powerful
		"micro",
		"shrinking",
		"giant",
		"colossal",
		"titanic",
		"enormous",
		"indestructible",
		"mighty",

		# back from the dead
		"undead",
		"reborn",
		"reanimated",

		# of a (mythological) earth civilization
		"Aztec",
		"Egyptian",
		"christian",
		"Mormon",
		"neanderthal",
		"heathen",
		"Norse",
		"soviet",
		"communist",

		# unseen / empty
		"invisible",
		"hollow",
		"immaterial",
		"empty",
		"phantasm",
		"phantom",
		"subterranean",
		"transparent",

		# a bit silly
		"teenage",
		"surfing", 
		"she-",

	]
}


grammar = tracery.Grammar(RULES)
grammar.add_modifiers(base_english)
for i in range(1000):
	title = grammar.flatten("#origin#")
	title = title.replace("womans", "women")
	title = title.replace("elfs", "elves")
	title = title.replace("  ", " ")
	print(title.strip().title())
